import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: [
    './app/**/*.{vue,js,ts}',
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.{vue,js,ts}',
    './pages/**/*.{vue,js,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#e4e2e1',
        'outline': '#7f766b',
        'on-error-container': '#93000a',
        'inverse-surface': '#30312e',
        'secondary': '#5f5e5e',
        'tertiary-container': '#b2bed4',
        'on-tertiary': '#ffffff',
        'primary-container': '#d4b996',
        'on-secondary-container': '#656464',
        'on-primary': '#ffffff',
        'on-surface': '#1b1c1a',
        'primary-fixed-dim': '#dec29f',
        'on-tertiary-fixed': '#101c2c',
        'surface-container': '#efeeea',
        'on-primary-container': '#5c492d',
        'on-surface-variant': '#4d463c',
        'inverse-primary': '#dec29f',
        'surface-variant': '#e4e2de',
        'secondary-fixed-dim': '#c8c6c6',
        'on-tertiary-container': '#414d5f',
        'inverse-on-surface': '#f2f0ed',
        'surface-container-highest': '#e4e2de',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#564428',
        'on-tertiary-fixed-variant': '#3c475a',
        'error': '#ba1a1a',
        'outline-variant': '#d0c5b8',
        'surface-dim': '#dbdad6',
        'background': '#fbf9f5',
        'surface-tint': '#705b3e',
        'primary-fixed': '#fbdeb9',
        'surface-container-high': '#eae8e4',
        'tertiary': '#535f72',
        'surface': '#fbf9f5',
        'tertiary-fixed': '#d7e3fa',
        'surface-bright': '#fbf9f5',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'surface-container-low': '#f5f3ef',
        'tertiary-fixed-dim': '#bbc7dd',
        'secondary-container': '#e4e2e1',
        'primary': '#705b3e',
        'on-error': '#ffffff',
        'on-primary-fixed': '#271903',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1b1c1a',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
} satisfies Config
